name: Bloodmoon
version: 0.8.2
main: net.refractored.bloodmoon.Bloodmoon
depend:
  - "eco"
softdepend:
  - "Multiverse-Core"
  - "WorldGuard"
  - "PlaceholderAPI"
api-version: 1.20
authors: [SpectralMemories, refractored, baconing]
description: A bloodmoon shines every couple of nights