name: BloodMoon
version: 0.8.2
main: net.refractored.bloodmoon.Bloodmoon
softdepend:
  - "Multiverse-Core"
  - "WorldGuard"
api-version: 1.20
authors: [SpectralMemories, refractored]
description: A BloodMoon shines every couple of nights