#Plugin version. Please do not tamper
ConfigVersion: 0.8.2
#Wether or not a BloodMoon happens in this world
#Requires a server restart upon changes
IsBlacklisted: false
#Enable or disable the leveling system of bloodmoons
#When disabled level one configs are used for evereything.
BloodmoonLevelsEnabled: true
#Sets a permanent BloodMoon in this world
#Obviously the interval option is ignored when this is on
PermanentBloodMoon: false
#Change the level of the PERMANENT bloodmoon
# This is ignored if levels are disabled or if permanent bloodmoons are disabled
PermanentBloodMoonLevel: 1
#Interval in days between BloodMoons
BloodMoonInterval: 5
#Do items despawn upon death?
ItemDespawnUponDeath: true
#Does experience despawn upon death?
ExperienceDespawnsUponDeath: true
#Maximum item amount to drop per mob death
ItemDropsMaximum: 4
#Minimum item amount to drop per mob death
ItemDropsMinimum: 0
#Mob experience drop multiplicator. Whole number only
ExperienceDropMult:
  - "1"
  - "1"
  - "1"
#Mob damage multiplier. Whole number only
MobDamageMultiplicator:
  - "3.0"
  - "3.0"
  - "3.0"
#Mob health multiplier. Whole number only
MobHealthMultiplicator:
  - "3.0"
  - "3.0"
  - "3.0"
#Should there be a lightning effect on player death?
LightningEffectOnPlayerDeath: true
#Adds a lightning effect when a mob dies
LightningEffectOnMobDeath: true
#Should there be a jingle when a BloodMoon ends?
PlaySoundUponBloodMoonEnd: true
#Should there be periodic creepy sounds during a BloodMoon?
PlayPeriodicSoundsDuringBloodMoon: true
#Adds a dark tone during a BloodMoon
DarkenSky: true
#Plays a sound when a player gets hit
PlaySoundUponHit: true
#Plays a particle effect when a mob and / or player gets hit
PlayerHitParticleEffect: true
MobHitParticleEffect: true
#Effect of rain and thunder during the BloodMoon
ThunderDuringBloodMoon: true
#Prevents sleeping during a BloodMoon
PreventSleeping: true
#Prevents mob created by spawner from dropping any reward
MobsFromSpawnerNoReward: false
#Prevents special effects from being applied when a player raises their shield
ShieldPreventsEffects: true
#Mob spawn rate during a BloodMoon.
#0 means no mob at all, 25 is average, and anything above 100 is honestly insane
BloodMoonSpawnMobRate: 25
#Decides if a zombie boss will spawn each BloodMoon
EnableZombieBoss: false
#When in a permanent BloodMoon, how long (in ticks) before respawning zombie boss after death?
#20 ticks equals a second, 24000 ticks equals a minecraft day
ZombieBossRespawn: 24000
ZombieBossDamage: 7
ZombieBossExpMultiplier: 10
ZombieBossHealth: 50
ZombieBossItemMultiplier: 10
#List of items that can drop, using the
#"[BloodmoonLvL],[Weight],[Item]" format
#The [Item] uses auxilor's eco item lookup. Read more here:
#https://plugins.auxilor.io/all-plugins/the-item-lookup-system
#The percent chance of an item dropping is equal to [item weight] / [total weight] * 100
#Here is an example of a special item drop with fire aspect I and sharpness III:
# - "diamond_sword name:Excalibur sharpness:3 fire_aspect:1"
DropItemList:
  - "1,10,iron_ingot 5"
  - "1,5,gold_ingot 2"
  - "1,5,gold_ingot 2"
  - "3,1,diamond 1"
  - "2,5,iron_block 1"
  - "2,2,gold_block 1"
#Enabling inheriting items allows items from bloodmoon level 1 to spawn in level 3:
#These are AOE powers affecting all players around the boss
InheritItems: true
#Accepted values are:
#LIGHTNING,[range],[cooldown]
#BLINK,[range],[cooldown]
#FIRE,[range],[cooldown],[duration]
#UNDERLING,[range],[cooldown],[amount]
#SPRINT,[duration],[cooldown],[amplifier]
#BLIND,[range],[cooldown],[duration]
#POISON,[range],[cooldown],[duration],[amplifier]
#WITHER,[range],[cooldown],[duration],[amplifier]
ZombieBossPowerSet:
  - "WITHER,12,20,5,1"
#Mob effects on hit. Format (with no spaces in between):
#[BloodmoonLevel],[Effect],[Duration in seconds],[Effect amplifier. Use 1 if you're unsure]
#Additional effects include: 'lightning'
ZOMBIEEffects:
  - "1,wither,7,1"
HUSKEffects:
  - "1,wither,7,1"
DROWNEDEffects:
  - "1,wither,7,1"
ZOMBIE_VILLAGEREffects:
  - "1,wither,7,1"
SKELETONEffects:
  - "1,slowness,3.5,1"
CREEPEREffects:
  - "1,lightning"
PHANTOMEffects:
  - "1,levitation,1.5,3"
SPIDEREffects:
  - "1,poison,4,1"
  - "1,nausea,6,9999"
ENDERMANEffects:
  - "1,slowness,2.5,2"
ZOMBIEBOSSEffects:
  - "1,wither,9,2"

#Thes commands will be ran right as a BloodMoon starts
#You must append a ;s, ;f or ;p at the end of the command:
#using ;s runs the command as the server. Once
#using ;f runs the command as the server, for each player. use $p as the player placeholder
#using ;p runs the command as the player, for each player. $p also applies
#For all options, $w will be replaced by the world name
#Note that these commands will be the very first and very last operations
#ran when starting and ending a BloodMoon
CommandsOnStart:
#  - "some command;s"
#Commands ran at the end of the BloodMoon
CommandsOnEnd:
#  - "command on player $p on world $w;p"

#Hordes parameter
#Are hordes even enabled in this world?
HordesEnabled: true
#The baseline spawn rate of hordes in ticks (1/5th of a second)
BaselineHordeSpawnrate: 800
#The variation of hordes spawn time in ticks
HordeSpawnrateVariation: 200
#Decides which mobs are allowed in hordes
HordeMobWhitelistLevel1:
  - "ZOMBIE"
  - "SKELETON"
  - "SPIDER"
HordeMobWhitelistLevel2:
  - "ZOMBIE"
  - "SKELETON"
  - "SPIDER"
HordeMobWhitelistLevel3:
  - "ZOMBIE"
  - "SKELETON"
  - "SPIDER"
  - "PHANTOM"
#The distance from players in block at which hordes will spawn
HordeSpawnDistance: 12
#The minimum number of mobs in a horde
HordeMinPopulation: 3
#The maximum number of mobs in a horde
HordeMaxPopulation: 10
